image: docker:latest

services:
- docker:dind

stages:
  - build
  - test
  - deploy

variables:
  SERVICE_API_TAG_NAME: registry.gitlab.com/laakso.mavrick/microservices/api:$CI_COMMIT_REF_NAME

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build-api:
  artifacts:
    paths:
    - service_api
  script:
  - docker build -t $SERVICE_API_TAG_NAME -f services/api/Dockerfile ./services/api
  - docker push $SERVICE_API_TAG_NAME
  # only:
  #   - $CI_COMMIT_MESSAGE =~ /\[build-api\]/